application: rapidspritetester
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /assets
  static_dir: ige/assets

- url: /ige
  static_dir: ige
  
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
